### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by radmiraal** [doctrine/couchdb-odm#112]
Hey guys, commit 610b900147aa0dc4eb6cefa1bfd04d7999c9ac0e broke my CouchDB ODM implementation for Flow. This is btw nothing you guys have to fix, but while debugging I wondered if you could start tagging new alpha versions in this package.

The last tag (alpha2) does not yet have a composer manifest, so if you use composer you're now forced to stick to master or a specific commit.

**Comment by beberlei** [comment]
@radmiraal Yes i can do that, makes sense to tag more :)

**Comment by beberlei** [comment]
Tagged a v1.0.0-alpha3 with the current state.
