### ISSUE TITLE
How to use CouchDB ODM with Silex?

### ISSUE THREAD

**Issue by casoetan** [doctrine/couchdb-odm#120]
Compliments of the season. 

I'm trying to configure this with silex but just can't crack it right now. Any guide,p or tuts would be great. 

Thanks.

**Comment by Ocramius** [comment]
Not an issue. Please refer to Stackoverflow or the mailing list for non-development questions.

**Comment by casoetan** [comment]
Hello @Ocramius I've searched the web for days and after your response, I did more digging, but nothing. Maybe I need to be specific, the error I keep getting is 

<code>
Class Package\\documents\\user is not a valid document or mapped super class.</code>

On debugging, I noticed this call in AnnotationDriver.php line 55

<code>$classAnnotations = $this->reader->getClassAnnotations($reflClass);</code>

Returns an empty array. I guess there maybe something wrong with my configuration, but can't seem to point it out. 

Any help will be appreciated. 
Thanks.
